spring.application.name=tgnews-api

spring.datasource.url=jdbc:postgresql://160.153.187.227:5432/TGNEWS
spring.datasource.username=postgres
spring.datasource.password=DataBase#001

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
